### ISSUE TITLE
uv_loop_size undefined when using cl-async:alet*

### ISSUE THREAD

**Issue by gitwn** [orthecreedence/cl-libuv#4]
cl-async:alet* calls to (LIBUV:UV-LOOP-SIZE) which gives error:
"The alien function "uv_loop_size" is undefined."

**Comment by orthecreedence** [comment]
@gitwn, sorry for the late response. Can you confirm you're using libuv >= v1.0.0 on your operating system?

**Comment by gitwn** [comment]
No problem.

I'm using libuv 0.10.22-2 on ubuntu 14.04.

If the libuv version is the problem then you can close the issue. It
will be some time before I get around to installing and testing newer
versions.

**Comment by orthecreedence** [comment]
Yep, that will do it. The API changed fairly significantly from v0.10.x to v1.x, and because the v1.x release was imminent, I didn't want to build cl-libuv against the old version, knowing I'd have to spend time upgrading it a few weeks later anyway.

For now, unless you are able to deal with the upgrade, you will have to use an older version of cl-async.
